# Generated by Django 4.2.7 on 2025-05-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_payment_payment_gateway_payment_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='encounter_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='medication_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
