# Generated by Django 4.2.7 on 2025-05-09 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_alter_labtest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='billing_status',
            field=models.CharField(choices=[('NOT_BILLED', 'Not Billed'), ('BILLED', 'Billed'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially Paid'), ('WAIVED', 'Waived')], default='NOT_BILLED', max_length=20),
        ),
        migrations.AddField(
            model_name='encounter',
            name='invoice_id',
            field=models.IntegerField(blank=True, help_text='ID của hóa đơn trong billing-service', null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', max_length=20),
        ),
    ]
